version: "3"

services:
  http-proxy-server:
    container_name: http-proxy-server
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/access.log:/var/log/nginx/access.log
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d/sites-available:/etc/nginx/conf.d/sites-available
      - ./config/conf.d/sites-enabled:/etc/nginx/conf.d/sites-enabled
    networks:
      - container-network
    restart: unless-stopped

networks:
  container-network:
    external: true
